version: '3'
services:
  backend:
    container_name: chat_backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: local
    ports:
      - "8080:8080"
    volumes:
      - "./backend/src:/app/"
    environment:
      LLM_CACHE_HOST: chat_redis_db
      LLM_CACHE_PORT: 6379
      CHAT_DB_HOST: chat_redis_db
      CHAT_DB_PORT: 6379
  front:
    container_name: chat_front
    build:
      context: ./front/
      dockerfile: Dockerfile
      target: local
    ports:
      - "8501:8501"
    volumes:
      - "./front/src:/app/"
    environment:
      CHAT_API_URL: http://chat_backend:8080
  redis:
    container_name: chat_redis_db
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
